---
name: validation // terraform

on:
  workflow_call:
    inputs:
      terraform-dir:
        description: "Where the terraform base directory is relative to the project root"
        default: "terraform"
        required: false
        type: string
      ansible-playbook:
        description: "Path to the ansible playbook to run (check mode and diff)"
        default: "ansible/main.yml"
        required: false
        type: string
      backend_cloud_credential_hostname:
        description: "The hostname of the cloud backend provider"
        required: false
        default: "app.terraform.io"
        type: string
      backend_cloud_credential_token:
        description: "If you're using terraform cloud as a backend, provide your credential here"
        required: false
        type: string
      workspace_name:
        description: "If you're using workspaces, provide the workspace name here"
        required: false
        type: string
    outputs:
      ansible:
        description: "Ansible output"
        value: ${{ jobs.ansible_diff.steps.ansible-dryrun.outputs.output }}

jobs:
  ansible_diff:
    name: pr // ansible
    runs-on: ubuntu-latest

    env:
      ANSIBLE_TF_DIR: ${{ inputs.terraform-dir }}
      ANSIBLE_TF_WS_NAME: ${{ inputs.workspace_name }}

      # If you use Terraform Cloud or Workspaces, uncomment this to set the workspace name for
      # the dynamic inventory scripts
      # ANSIBLE_TF_WS_NAME:

    steps:
      - name: pr // ansible // checkout
        uses: actions/checkout@v3

      - name: pr // ansible // setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: pr // ansible // terraform-setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform-dir: ${{ inputs.terraform-dir }}
          backend_cloud_credential_hostname: ${{ inputs.backend_cloud_credential_hostname }}
          backend_cloud_credential_token: ${{ inputs.backend_cloud_credential_token }}

      - name: pr // ansible // terraform-init
        id: terraform-init
        run: terraform init
        working-directory: ${{ inputs.terraform-dir }}

      - name: pr // ansible // dryrun
        id: ansible-dryrun
        uses: techjavelin/iac-action-ansible@v1
        with:
          playbook: ${{ inputs.ansible-playbook }}
          options: |
            --inventory ansible/inventory/terraform-inventory/teraform.py
            --inventory ansible/inventory/static
          check_mode: "true"
          diff: "true"
          use_pipenv: "true"
          no_color: "true"
